import { API_CONFIG, API_ENDPOINTS } from "../../constants/config";

export const ENDPOINTS = {
  COLLECTIONS_POPULAR: API_ENDPOINTS.COLLECTIONS.POPULAR,
  COLLECTIONS_LATEST: API_ENDPOINTS.COLLECTIONS.LATEST,
  COLLECTIONS_DETAILS: (id) => API_ENDPOINTS.COLLECTIONS.DETAILS(id),
  COLLECTIONS_SEARCH: API_ENDPOINTS.COLLECTIONS.SEARCH,
  COLLECTIONS_SUGGEST: API_ENDPOINTS.COLLECTIONS.SUGGEST,
  COLLECTIONS_FILTERS: API_ENDPOINTS.COLLECTIONS.FILTERS,
  COLLECTIONS_RECOMMEND: API_ENDPOINTS.COLLECTIONS.RECOMMEND,

  // ✅ VECTOR dipisah dengan benar
  VECTOR_VECTORIZE: API_ENDPOINTS.VECTOR.VECTORIZE,

  // Absolute helpers
  ABSOLUTE: {
    BASE_URL: API_CONFIG.BASE_URL,
    COLLECTION_DETAILS_URL: (id) => `${API_CONFIG.BASE_URL}${API_ENDPOINTS.COLLECTIONS.DETAILS(id)}`,
  },
};

